/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testplugin_JniUtils */

#ifndef _Included_com_example_testplugin_JniUtils
#define _Included_com_example_testplugin_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testplugin_JniUtils
 * Method:    getsum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testplugin_JniUtils_getsum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
